### ISSUE TITLE
import { OpenAPIObject } from "openapi3-ts/src/model/openapi31" doesn't work with mocha and ESM

### ISSUE THREAD

**Issue by BryanHunt** [metadevpro/openapi3-ts#107]
If you are building an ESM module and you use the import format:

```ts
import { OpenAPIObject } from "openapi3-ts/src/model/openapi31";
```

and use mocha with:

```json
{
  "loader": "ts-node/esm"
}
```

 unit tests will fail.

The "fix" is to use the import format:

```ts
import { oas31 } from "openapi3-ts";
```

Since the second format works, I don't expect any code change here.  I'm mainly creating this issue in case others run into the same problem.

It might be good to update the readme to note this.

**Comment by pjmolina** [comment]
Thanks, I will do.
