### ISSUE TITLE
Cannot import `oas31` using ESM in `openapi3-ts@4.1.1`

### ISSUE THREAD

**Issue by invakid404** [metadevpro/openapi3-ts#114]
While trying to upgrade to `openapi3-ts@4.1.1` in my project, I suddenly started getting this error on all my imports:

```
import { oas31 } from 'openapi3-ts';
         ^^^^^
SyntaxError: Named export 'oas31' not found. The requested module 'openapi3-ts' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'openapi3-ts';
const { oas31 } = pkg;
```

I'm guessing this is happening because my project is ESM. It used to work fine with `openapi3-ts@4.0.4`.

I'm using TypeScript 5.0.4, and my `tsconfig.json` looks like this:

```json
{
  "compilerOptions": {
    "lib": ["ESNext", "dom"],
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "NodeNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "outDir": "dist"
  }
}
```

**Comment by koooge** [comment]
Hi,
`"moduleResolution": "node16",` would work. We need to update the README.

refs: https://github.com/metadevpro/openapi3-ts/pull/111

**Comment by invakid404** [comment]
What if I want to use `NodeNext` though? Switching to `Node16` is not an option for my project.

**Comment by koooge** [comment]
You can use it since it is the exact same. https://www.typescriptlang.org/tsconfig#moduleResolution

**Comment by invakid404** [comment]
But if it's the exact same, why wouldn't it work in the first place? I'm confused :D

**Comment by koooge** [comment]
Yours is not nodenext ->  `"moduleResolution": "Node",`.
