### ISSUE TITLE
Validation error: `examples` must be an array

### ISSUE THREAD

**Issue by RobinTail** [metadevpro/openapi3-ts#127]
Using the recent version (4.2.0) I'm getting OpenAPI 3.1 [validation](https://editor-next.swagger.io/) error regarding SchemaObject's `examples` being object instead of array.

![image](https://github.com/metadevpro/openapi3-ts/assets/13189514/5a7703d6-31db-4843-9a08-1b51932c20c4)

It's caused by the changes in this PR: https://github.com/metadevpro/openapi3-ts/pull/124
In that PR `examples` were changed from `any[]` to `ExamplesObject`.

The [specification](https://swagger.io/specification/) refers to this document: 
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#page-22
which as well as the validator says that `examples` must be array.

![image](https://github.com/metadevpro/openapi3-ts/assets/13189514/69be2528-95d5-4583-9680-397721e7ea63)

I'm trying to find the source of truth and/or where the mistake is.

@kkolstad  || @pjmolina ,
could you tell me please which information the changes from #124 are based on?
Is there any other RFC or revision that changed the `examples` from array to object?
Is that an issue of the validator or of the PR?

**Comment by kkolstad** [comment]
I based those changes off the OpenAPI Specification [3.0](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#fixed-fields-6) and [3.1](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-6)

<img width="1043" alt="Screenshot 2023-12-21 at 2 31 57 PM" src="https://github.com/metadevpro/openapi3-ts/assets/1631066/772e4cbd-89a1-4daa-acb0-c9ddaaf03961">

**Comment by RobinTail** [comment]
The `examples` you refer to, are NOT the property of `SchemaObject`.
This is the `examples` property of ComponentsObject, @kkolstad 

![image](https://github.com/metadevpro/openapi3-ts/assets/13189514/ff979b9d-abfe-497b-873c-684e03c3e436)

![image](https://github.com/metadevpro/openapi3-ts/assets/13189514/985c5f70-1cec-4ff4-b0d2-a032e1c28abd)

**Comment by RobinTail** [comment]
@pjmolina , it seems that the changes made by #124 are wrong, because the property `examples` exists in multiple interfaces. In most cases it's really the `ExampleObject`, but within the `SchemaObject` `examples` still has to be an array.
I'm suggesting to revert #124 .

**Comment by kkolstad** [comment]
@RobinTail I see my mistake now. Thanks for pointing that out. Sorry for the bug 😄

**Comment by pjmolina** [comment]
Thansk for the analysis @RobinTail

**Comment by vafanassieff** [comment]
Hey @kkolstad when I read the Open API spec 3.1, i see that [ParameterObject](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#parameter-object) has a `examples` field that can be set to `Map[ string, Example Object | Reference Object]`

How do i use this type to add examples to my Open Api spec ?

Best

**Comment by RobinTail** [comment]
What the call `Map` is the `Record` in Typescript, @vafanassieff .
So you assign `examples` with object having keys as strings and values as `ExampleObject | ReferenceObject`

```ts
...
examples: {
  example1: {
    value: "something"
  }
}
```
