### ISSUE TITLE
Wrong type for security fields

### ISSUE THREAD

**Issue by willshowell** [metadevpro/openapi3-ts#18]
First thank you so much for this library - it's been a big time saver! 😄 

I think I've found the following bugs:

```ts
interface OpenAPIObject {
 ... 
 security: SecurityRequirementObject // should be SecurityRequirementObject[]
}

interface OperationObject {
 ...
 security: SecurityRequirementObject // same thing here: SecurityRequirementObject[]
}
```

Refs:
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#openapi-object
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#operation-object

**Comment by pjmolina** [comment]
Thanks for caching it @willshowell 
Added!
