### ISSUE TITLE
Documentation - Usage

### ISSUE THREAD

**Issue by thomasdavis** [metadevpro/openapi3-ts#26]
Cool looking project, but not entirely sure of all the use cases. 

Currently implementing contract testing using Open API v3 with Express and writing all our own utils. We'd love to use Typescript as it makes a lot of sense for contract testing.

**Comment by pjmolina** [comment]
Great! 
If missing a specific feature or documentation let me know.

**Comment by natarajanmca11** [comment]
Please let us know how to use this library. Any documentation is available for this package?

**Comment by pjmolina** [comment]
@natarajanmca11 At this moment, the best doc is to take a look to [tests](https://github.com/metadevpro/openapi3-ts/blob/master/src/dsl/OpenApiBuilder.spec.ts). There you can see how to build OpenAPI contracts in a fluent way.
