### ISSUE TITLE
Is it time for 1.0.0 release yet?

### ISSUE THREAD

**Issue by bajtos** [metadevpro/openapi3-ts#29]
I would like to propose bumping up the major version of this package from `0` to `1`, to signalize consumers we are ready for general use.

As [semver](https://semver.org/#how-do-i-know-when-to-release-100) says:
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

There are already more than 10 projectsdepending on `openapi3-ts` and the stability of its API, see https://www.npmjs.com/browse/depended/openapi3-ts.

@pjmolina thoughts?

**Comment by pjmolina** [comment]
You are right @bajtos ! 
After some months of incubation and bug fixing with the help of the community, I think is pretty stable.
Let's do it and move to version 1.0.0.

**Comment by bajtos** [comment]
Awesome, thank you @pjmolina ❤️
