### ISSUE TITLE
Wrong types for SchemaObject.properties/.allOf/.oneOf/.anyOf ?

### ISSUE THREAD

**Issue by martinluetke** [metadevpro/openapi3-ts#3]
The swagger-schema-official implementation for Swagger 2.0 described *.properties* thus:

`properties?: {[propertyName: string]: Schema};`

Also *.allOf*, *.oneOf*, and *.anyOf* are lists.

Therefore I would expect their types to be:

```
allOf?: (SchemaObject | ReferenceObject)[];
oneOf?: (SchemaObject | ReferenceObject)[];
anyOf?: (SchemaObject | ReferenceObject)[];
properties?: {[propertyName: string]: (SchemaObject | ReferenceObject)};
```
Am I missing something?

**Comment by pjmolina** [comment]
Thanks for pointing out @martinluetke   Fixed and published as version 0.3.1
