### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by Sergey-Ryabov** [metadevpro/openapi3-ts#36]
Hello.
Can I use it for generate API layer for Angular from remote openapi.json? Could you add usage examples?

**Comment by pjmolina** [comment]
Hi Sergey. 

OpenAPI3-ts exposes the typed object model for a OpenAPI document in TypeScript.
It also exposed a basic DSL to build an OpenAPI document.
From this starting point some basic use cases include:
- Generate OpenAPI document on the fly depending on your needs
- Build a Validator for OpenAPI

If you want to do some codegen to a particular framework (like Angular) you can for sure implement a visitor to emit the code you need. On the other hand I suggest also you to take a look to current generators on [swagger-codegen](https://github.com/swagger-api/swagger-codegen) and [openapi-tools](https://openapi.tools/)
