### ISSUE TITLE
how to remove/update a path? 

### ISSUE THREAD

**Issue by insub** [metadevpro/openapi3-ts#72]
I don't seem to see the relevant function in the dsl.
thank.

**Comment by pjmolina** [comment]
Hi @insub 
You are right, currently, there is no function for removing or updating a path.
This lib is oriented to support the following use case: **to create an inmutable tree** spec and then serialize it to JSON or Yaml.

What is your use case? 
Why do you need to remove or update a path you already has setup previously?

It could be added to the library, for sure, but then, I guess, we will need to add remove/update support also for others concepts like tags, responses, types, etc.
