### ISSUE TITLE
v3.0: `exclusiveMaximum` must be a boolean

### ISSUE THREAD

**Issue by RobinTail** [metadevpro/openapi3-ts#83]
[Lines 306 and 308](https://github.com/metadevpro/openapi3-ts/blame/master/src/model/OpenApi.ts#L306) have been changed in this commit:
https://github.com/metadevpro/openapi3-ts/commit/e7a08516a86620a66a16f4552d5b9affd6c77987

These changes have been released in version 3.0.0.

However, according to this spec, `exclusiveMaximum` must be boolean:
https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00#section-5.3

More than that, the [Swagger validator](https://editor.swagger.io/) complains about numeric value as well:
![image](https://user-images.githubusercontent.com/13189514/184887724-3ac66ff2-49ad-4ec2-b82a-67f44347c898.png)

I think that the mentioned commit should be reverted.
Otherwise, could you please clarify what was the reason for that change?

**Comment by RobinTail** [comment]
CC @OrIOg

**Comment by RobinTail** [comment]
Ok, I found the PR that describes the reason:
https://github.com/metadevpro/openapi3-ts/issues/78

And this looks a bit strange to me, since my link to the spec is taken from the swagger.io website:
https://swagger.io/specification/

The document clearly says that the property MUST be boolean:
https://datatracker.ietf.org/doc/html/draft-wright-json-schema-validation-00

However the one referred in the PR says it must be a number:
https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.2.3

Presuming that the one in the PR is newer, it's still questionable how to deal with the complains in Swagger validator (see the screenshot)

**Comment by RobinTail** [comment]
Here is another link to the documentation that describes `exclusiveMaximum` as boolean:
https://swagger.io/docs/specification/data-models/data-types/?sbsearch=exclusiveMaximum

It's based on OpenAPI 3.0 and as per my understanding it should not be breaking changes in 3.1 as well.
So, it's still confusing.

**Comment by RobinTail** [comment]
Holy Moly, they really changed it without any backward compatibility:

https://www.ietf.org/rfcdiff?url1=draft-wright-json-schema-validation-00&url2=draft-wright-json-schema-validation-01&difftype=--html

![image](https://user-images.githubusercontent.com/13189514/184909527-10f08736-4b23-4ea9-8860-d5d2eb68acb2.png)

**Comment by pjmolina** [comment]
Looks like the change is coming from different versions of JSON Schema. OpenAPI is not redefining them, but using them directly from JSON Schema.
See: https://json-schema.org/understanding-json-schema/reference/numeric.html

- Previous versions used `exclusiveMaximum` and `exclusiveMinimum` as booleans in combination with `maximum` and `minimum`. Probably used at Swagger. 2.x.
- Draft 4 in JSON Schema changed and broke the compatibility to be: `exclusiveMaximum` and `exclusiveMinimum` numbers.

Latest spec [OpenAPI 3.1.0](https://spec.openapis.org/oas/latest.html) uses [JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.2.1)  (the number version)

So, my best guess is we should stick to `numbers`.

Take in mind (last time I checked) Swagger Editor (from swagger.io) was still supporting spec. v2. and not yest 3.x

**Comment by RobinTail** [comment]
Yeah, I see.
So, if the library is only `3.1` compatible, should we reflect it on `version` here, for example:
https://github.com/metadevpro/openapi3-ts/blob/master/src/dsl/OpenApiBuilder.ts#L16

And there also a lot of comments/jsdoc that refer to `3.0`, while they are so different and backward incompatible.

What do you think?

Also, which tool would you recommend to validate `3.1` specification?
Swagger.io validates `3.0.x` only.

@pjmolina

**Comment by pjmolina** [comment]
Indeed, we can enforce 3.1.0 but also thinking about relaxing the type for `exclusiveMaximum` and `exclusiveMinimum` to be `number | boolean` to help people to transition from OpenAPI 3.0 (boolean) to 3.1. (number)

What do you think it would be more useful? 
What do you need in your use cases @RobinTail 3.0.0 or 3.1.0?

**Comment by pjmolina** [comment]
A good list of validators and compatibility is maintained here: https://openapi.tools/#data-validators
Support for 3.1 has a "slow adoption" so I am more inclined to still support 3.0 and 3.1 in this lib if we can handle the complexity.

**Comment by RobinTail** [comment]
> Indeed, we can enforce 3.1.0 but also thinking about relaxing the type for exclusiveMaximum and exclusiveMinimum to be number | boolean to help people to transition from OpenAPI 3.0 (boolean) to 3.1. (number)
> What do you think it would be more useful?

Well, I believe that ideally, in a case like this, the type should depend on the version literal and be generic.

For example, consider this:

```typescript
type OpenApiVersion = `3.${number}.${number}`;

export interface OpenAPIObject<V extends OpenApiVersion> {
  openapi: V;
  // ...
}

export interface SchemaObject<V extends OpenApiVersion> {
  // ...
  exclusiveMaximum?: V extends `3.1.${number}` ? number : boolean;
}
```

It requires at least Typescript 4.1 to support type literals.
And perhaps more entities would have to become generic.
But the benefit of it — keeping the single but generic type declaration.

I will think more on other ways too.
@pjmolina

**Comment by RobinTail** [comment]
> What do you need in your use cases @RobinTail 3.0.0 or 3.1.0?

For my case, I need to provide users of my library with a tool that generates the specification of their API, that could be used for the following cases:
- general documentation to share between BE and FE developers
- development support on the tool level, to visualize the schema and perform sample API requests:
  - [WebStorm OpenAPI plugin](https://plugins.jetbrains.com/plugin/14394-openapi-specifications)
  - [Swagger editor](https://editor.swagger.io/)
- testing and mocking
  - [Postman OpenAPI integration](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/)
 
I'm not sure at the moment which versions are supported by Webstorm and Postman, but Swagger still only support 3.0.
I'm going to find out and let you know soon.
Thank you @pjmolina

**Comment by RobinTail** [comment]
It's ok, @OrIOg . I prepared another one: #85 , according to @pjmolina vision. It's much simpler and might fulfill all needs.
