### ISSUE TITLE
4.0: the module exports OAS 3.1 only

### ISSUE THREAD

**Issue by RobinTail** [metadevpro/openapi3-ts#98]
I'm a bit confused.
If possible, could you please clarify how to operate OAS 3.0, if the module exports DSL and the model of 3.1 only?
Should I`import from "openapi3-ts/dist/cjs/model/openapi30"` directly or what exactly is supposed?
Maybe it should be explained in the changelog or Readme.

https://github.com/metadevpro/openapi3-ts/blob/26e17404b0844ff437487e830608eeca07d50b41/src/dsl/index.ts#L1

https://github.com/metadevpro/openapi3-ts/blob/26e17404b0844ff437487e830608eeca07d50b41/src/model/index.ts#L1

https://github.com/metadevpro/openapi3-ts/blob/26e17404b0844ff437487e830608eeca07d50b41/package.json#L7

**Comment by RobinTail** [comment]
CC @pjmolina ?

**Comment by pjmolina** [comment]
Hi. Sorry for the delay @RobinTail 
Yes. The default export points to v. 3.1.
But when needed yo consume v 3.0 you can import from:

```typescript
import from "openapi3-ts/dist/cjs/model/openapi30"; 
import from "openapi3-ts/dist/cjs/dsl/openapi-builder30";
```

Yes, agreed. We should add it to the Readme also.

**Comment by pjmolina** [comment]
Docs updated. Published as `v. 4.0.1`. 
Please it checkout @RobinTail to see if now is clearer.
Thanks!

**Comment by RobinTail** [comment]
> But when needed yo consume v 3.0 you can import from:
> ```
> import * from "openapi3-ts/dist/cjs/model/openapi30"; 
> import * from "openapi3-ts/dist/cjs/dsl/openapi-builder30";
> ```

I see. Unfortunately, this does not work quite well when using such imports for the further compilations both to CJS and ESM.

Would it be possible, to have re-export everything from the root index file under different names?

Thus, I wouldn't need to specify `/cjs` and `/esm` explicitly.
Something like `import { OpenAPIBuilder30 } from "openapi3-ts";`.

Or maybe using namespaces?

Something like `namespace v30 {} ` for both model and dsl.

**Comment by pjmolina** [comment]
Yes, I think we can do it, as we can just break compatibility. 
A rename for the v. 3.0 should work. Let's try it.
